Repository HexaTeam-By-Epitech/area, pull requests merged in 2025-09, with the labels that each got.

#33 GitHub templates
  .github/CODE_OF_CONDUCT.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: Documentation

#37 Feat/auth/email password
  area-backend/.env.example
  area-backend/package.json
  area-backend/src/app.module.ts
  area-backend/src/main.ts
  area-backend/src/modules/auth/auth.controller.ts
  area-backend/src/modules/auth/auth.module.ts
  area-backend/src/modules/auth/auth.service.ts
  area-backend/src/modules/auth/dto/login.dto.ts
  area-backend/src/modules/auth/dto/register.dto.ts
  area-backend/src/modules/users/dto/create-user.dto.ts
  area-backend/src/modules/users/dto/update-user.dto.ts
  area-backend/src/modules/users/users.controller.ts
  area-backend/src/modules/users/users.module.ts
  area-backend/src/modules/users/users.service.ts
  area-backend/src/prisma/prisma.module.ts
  area-backend/src/prisma/prisma.service.ts
  area-backend/src/prisma/schema.prisma
  area-backend/test/auth/auth.controller.spec.ts
  area-backend/test/auth/auth.e2e.spec.ts
  area-backend/test/auth/auth.service.spec.ts
  area-backend/test/jest.config.ts
Labels: Backend

#38 Feat/action manager
  .gitignore
  area-backend/.gitignore
  area-backend/eslint.config.mjs
  area-backend/package-lock.json
  area-backend/src/app.module.ts
  area-backend/src/modules/action/action.controller.ts
  area-backend/src/modules/action/action.module.ts
  area-backend/src/modules/action/action.service.ts
  area-backend/src/modules/manager/manager.controller.ts
  area-backend/src/modules/manager/manager.module.ts
  area-backend/src/modules/manager/manager.service.ts
  area-backend/src/modules/reaction/reaction.controller.ts
  area-backend/src/modules/reaction/reaction.module.ts
  area-backend/src/modules/reaction/reaction.service.ts
Labels: Backend

#46 Feat/front/login page
  area-web/.gitignore
  area-web/README.md
  area-web/index.html
  area-web/package-lock.json
  area-web/package.json
  area-web/public/vite.svg
  area-web/src/App.vue
  area-web/src/components/Login.vue
  area-web/src/components/Register.vue
  area-web/src/main.js
  area-web/src/style.css
  area-web/vite.config.js
Labels: Frontend

#54 Feat/front/oa2 login register
  area-backend/src/modules/auth/auth.controller.ts
  area-web/.gitignore
  area-web/index.html
  area-web/src/App.vue
  area-web/src/components/Login.vue
  area-web/src/components/Register.vue
  area-web/src/utils/googleAuth.ts
Labels: Frontend

#55 Feat/front/home page
  area-web/src/App.vue
  area-web/src/components/Home.vue
  area-web/src/components/Login.vue
  area-web/src/components/Register.vue
  area-web/src/utils/googleAuth.ts
Labels: Frontend

#79 Refactor auth module and add Spotify API helper
  area-backend/db/schema.sql
  area-backend/db/seed.sql
  area-backend/src/modules/actions/spotify/like.service.ts
  area-backend/src/modules/auth/auth.controller.ts
  area-backend/src/modules/auth/auth.email.controller.ts
  area-backend/src/modules/auth/auth.google.identity.controller.ts
  area-backend/src/modules/auth/auth.google.linking.controller.ts
  area-backend/src/modules/auth/auth.module.ts
  area-backend/src/modules/auth/auth.service.ts
  area-backend/src/modules/auth/auth.spotify.linking.controller.ts
  area-backend/src/modules/auth/auth.token.controller.ts
  area-backend/src/modules/auth/providers/ProviderRegistry.ts
  area-backend/src/modules/auth/providers/TokenCryptoUtil.ts
  area-backend/src/modules/auth/providers/identity/GoogleIdentityProvider.ts
  area-backend/src/modules/auth/providers/identity/IdentityProvider.ts
  area-backend/src/modules/auth/providers/oauth2/GoogleOAuthLinkProvider.ts
  area-backend/src/modules/auth/providers/oauth2/OAuth2LinkProvider.ts
  area-backend/src/modules/auth/providers/oauth2/SpotifyOAuthLinkProvider.ts
  area-backend/src/modules/users/users.service.ts
  area-backend/src/prisma/migrations/20250923143500_split_oauth/migration.sql
  area-backend/src/prisma/migrations/20250923145457_split_oauth/migration.sql
  area-backend/src/prisma/schema.prisma
  area-web/.gitignore
Labels: Backend
